import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
} from 'typeorm';

@Entity('encryption_metadata')
export class EncryptionMetadata {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column()
  algorithm!: string;

  @Column()
  keyVersion!: string;

  /**
   * Encrypted data encryption key.
   */
  @Column({ type: 'text' })
  encryptedDataKey!: string;

  /**
   * Authentication tag generated by AES-GCM.
   */
  @Column({ type: 'text' })
  authTag!: string;

  @Column({ type: 'text' })
  iv!: string;

  @Column()
  storageRef!: string;

  @CreateDateColumn()
  createdAt!: Date;
}
